### ISSUE TITLE
Issues when uploading large files

### ISSUE THREAD

**Issue by prasadKodeInCloud** [peerlibrary/meteor-aws-sdk#10]
When uploading large files (over 10 mb)  to aws, this error can be seen in server log "AWS S3 message=The difference between the request time and the current time is too large". After that meteor got restarted.

This issue did not exist in "1.5.1.1" version. reverting package back to this version fixed the issue.

Tested on meteor 0.8.1.3

**Comment by mitar** [comment]
No feedback. Closing.
