### ISSUE TITLE
Async Fiber Error

### ISSUE THREAD

**Issue by warsamebashir** [peerlibrary/meteor-aws-sdk#14]
I am most recently with this package getting Fiber errors which I wasn't when I had first tested and played with it successfully. The error:

```` Javscript

Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
````

I thought this package already wraps all calls in an `Async` or did I miss something ?

**Comment by mitar** [comment]
?

Does it work for you or not? And yes, it should wrap all, but then you should not be passing your own callbacks in.

**Comment by warsamebashir** [comment]
I needed to pass my own callback due to processing after uploading the data and are currently attempting it with `wrapAsync`

https://gist.github.com/warsamebashir/a6a749d8abc29f3bec8e

**Comment by mitar** [comment]
You are doing it wrong. :-)

With "sync" version you just do whatever you want after a blocking call. No need for callbacks.

**Comment by warsamebashir** [comment]
Mhmm, so with `sync` version here, I ultimately wanted to make sure the `s3.upload` call finishes before making server side `Meteor.method` calls.

**Comment by warsamebashir** [comment]
@mitar is `s3.upload` the sync version or is there an equivalent `sync` version like the other functions available from the AWS sdk ?

**Comment by mitar** [comment]
Sync versions have `Sync` suffix.

**Comment by warsamebashir** [comment]
Maybe I am a little bit confused but I am getting an error when I use it like so:

```` Javascript

 s3.uploadSync(file, options, function(error, data) {
           
        });

````

**Comment by mitar** [comment]
You can try: https://github.com/peerlibrary/meteor-aws-sdk/issues/8#issuecomment-52397090

**Comment by mitar** [comment]
I released a new version.

**Comment by mitar** [comment]
Try `peerlibrary:aws-sdk@2.1.14_2` and it should work. So you should do something like:

```
var data = s3.uploadSync(file, options);
...
```

**Comment by warsamebashir** [comment]
Thanks, i will give this a shot.
