### ISSUE TITLE
SQS.sendMethodSync bug?

### ISSUE THREAD

**Issue by Siyfion** [peerlibrary/meteor-aws-sdk#15]
When attempting to use the `sendMessageSync` method, I get the following error:

`MissingRequiredParameter: Missing required key 'QueueUrl' in params`

Here's some example code...
```javascript
var sqs = new AWS.SQS();
var sentMessage = sqs.sendMessageSync({
  QueueUrl: process.env.SQS_PDF_REQ,
  MessageBody: JSON.stringify(pdfMsg),
  DelaySeconds: 0
});
```

**Comment by mitar** [comment]
This error you get if your `process.env.SQS_PDF_REQ` is false/not defined. If I put there a constant string it works for me.
