### ISSUE TITLE
AWS settings missing

### ISSUE THREAD

**Issue by kidsil** [peerlibrary/meteor-aws-sdk#17]
I've added my credentials to `~/.aws/credentials`, and I've tested it with vanilla JS and it worked.
For some reason, I'm still not getting the *Meteor.settings.AWS* object.
which means the following script:

    if ( Meteor.settings.AWS ) {
    	AWS.config.update({
    		accessKeyId: Meteor.settings.AWS.accessKeyId,
    		secretAccessKey: Meteor.settings.AWS.secretAccessKey
    	});
    } else {
    	console.warn("AWS settings missing!!");
    }

returns  `AWS settings missing`

**Comment by mitar** [comment]
Why would `Meteor.settings.AWS` be populated from `~/.aws/credentials`? `Meteor.settings.AWS` is populated from `--settings` argument to `meteor run`. Read [here](http://docs.meteor.com/#/full/meteor_settings).

**Comment by rodamn** [comment]
Made this mistake too per AWS-SDK documentation recommendation. Should address this common mistake and/or provide recommended approaches in the README?

**Comment by mitar** [comment]
Pull requests welcome. :-)

**Comment by justinmchase** [comment]
Its standard operating procedure to use AWS_PROFILE to select a profile found in the ~/.aws/credentials file. That way you can switch between profiles easily.
