### ISSUE TITLE
 Missing credentials in config

### ISSUE THREAD

**Issue by Kamshak** [peerlibrary/meteor-aws-sdk#21]
When trying to access a bucket to delete a file i get the error " Missing credentials in config" even though credentials are set.

    AWS.config.update({
        accessKeyId: Meteor.settings.AWSAccessKeyId,
        secretAccessKey: Meteor.settings.AWSSecretAccessKeyId,
        region: Meteor.settings.AWSRegion
    });

  Meteor.methods({
    updateAvatar: function(avatarName) {
      if (!Meteor.userId()) {
        throw new Meteor.Error(401, 'Unauthorized', 'Please login');
      }

      var oldAvatar = Meteor.user().profile.avatarName;
      if (oldAvatar) {
        var s3 = new AWS.S3();
        var params = {
          Bucket: Meteor.settings.AWSBucket,
          Key: oldAvatar
        };

        s3.deleteObjectSync(params);
      }
  )}

The error

```
I20150919-19:01:03.520(1)? Exception while invoking method 'updateAvatar' TimeoutError: Missing credentials in config
I20150919-19:01:03.520(1)?     at Object.Future.wait (C:\Users\Valentin\AppData\Local\.meteor\packages\meteor-tool\1.1.4
\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
I20150919-19:01:03.520(1)?     at [object Object].f [as deleteObjectSync] (packages/peerlibrary:blocking/server.js:18:1)

I20150919-19:01:03.521(1)?     at [object Object].Meteor.methods.updateAvatar (app\server\users.js:38:10)
I20150919-19:01:03.521(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150919-19:01:03.522(1)?     at packages/ddp/livedata_server.js:648:1
I20150919-19:01:03.522(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150919-19:01:03.522(1)?     at packages/ddp/livedata_server.js:647:1
I20150919-19:01:03.523(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150919-19:01:03.523(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646
:1)
I20150919-19:01:03.523(1)?     at packages/ddp/livedata_server.js:546:1
I20150919-19:01:03.524(1)?     - - - - -
I20150919-19:01:03.524(1)?     at ClientRequest.<anonymous> (C:\Users\Valentin\AppData\Local\.meteor\packages\peerlibrar
y_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\http\node.js:56:34)
I20150919-19:01:03.524(1)?     at ClientRequest.g (events.js:180:16)
I20150919-19:01:03.525(1)?     at ClientRequest.emit (events.js:92:17)
I20150919-19:01:03.525(1)?     at Socket.emitTimeout (http.js:1802:10)
I20150919-19:01:03.525(1)?     at Socket.g (events.js:180:16)
I20150919-19:01:03.526(1)?     at Socket.emit (events.js:92:17)
I20150919-19:01:03.526(1)?     at Socket._onTimeout (net.js:327:8)
I20150919-19:01:03.526(1)?     at _makeTimerTimeout (timers.js:429:11)
I20150919-19:01:03.527(1)?     at Timer.unrefTimeout [as ontimeout] (timers.js:493:5)
```

**Comment by mitar** [comment]
Is this related to #17? Are you sure you are setting credentials? You should print out the:

```
{
    accessKeyId: Meteor.settings.AWSAccessKeyId,
    secretAccessKey: Meteor.settings.AWSSecretAccessKeyId,
    region: Meteor.settings.AWSRegion
}
```

So I have seen this error when people do not set Meteor settings correctly.

**Comment by Kamshak** [comment]
Yep, this is definitely populated correctly i use the same settings for Slingshot S3 file upload which works just fine. I also tried printing them and setting them again just before the request but no luck :/

**Comment by mitar** [comment]
Hm, no idea. It would be great if you could make a reproduction or even a test case.

**Comment by Kamshak** [comment]
After creating a test case I noticed that I did infact make a mistake configuring the credentials, secretAccessKey: Meteor.settings.AWSSecretAccessKeyId should be secretAccessKey: Meteor.settings.AWSSecretAccessKey. 

Sorry about that.
