### ISSUE TITLE
Display on browser the results of a query

### ISSUE THREAD

**Issue by paolopennisi** [peerlibrary/meteor-aws-sdk#22]
Hi,
I am new to Meteor, but what I am try to do it should be that complex. I want to read from a table in DynamoDB and display the results in the browser window.

What I am doing at the moment is the following:
```meteor
if (Meteor.isServer) {
      var db = new AWS.DynamoDB();
      var params = {...};
      db.query(params, function(err, data){
          if (err) console.log(err, err.stack); // an error occurred
          else     console.log(data);
      }); 
}

if (Meteor.isClient) {
  Template.body.helpers({
    tasks: [
      // I'd like to display here the data from my query
    ]
  });       
}
```

Any help would be appreciated. Thanks.

**Comment by mitar** [comment]
Sorry, use Meteor forum or StackOverflow for such beginner questions.

You should do a server-side publish to publish data from DynamoDB to Meteor client side.
