### ISSUE TITLE
Calling SES API - GetSendStatistics

### ISSUE THREAD

**Issue by aadamsx** [peerlibrary/meteor-aws-sdk#25]
Is there a package similar to this that allows me to call the AWS SES API, such as GetSendStatistics to get data points on how many emails we send out and at what time?

**Comment by aadamsx** [comment]
Sorry, I found it.  It looks like this package does support.  Any chance you'd provide a rough example of how i'd make a API call to GetSendStatistics using the AWS global?

**Comment by mitar** [comment]
This package supports everything official Amazon package supports. You will have to consult documentation there.
