### ISSUE TITLE
Using IAM roles

### ISSUE THREAD

**Issue by willkessler** [peerlibrary/meteor-aws-sdk#27]
Hi, package is great but doesn't seem to leverage IAM roles. However aws-sdk run from node does. Is there a way to set things up so you can skip using accessKey/secretAccesskey and just use the IAM role of the server? Thank you!

**Comment by mitar** [comment]
I have no idea, this package just wraps NPM module. If it works there, it should work here as well.

**Comment by gkrizek** [comment]
@willkessler The AWS-SDK can read from your server config files.

Put this into your credentials file on the server:  (`~/.aws/credentials`)

```
[profile prodaccess]
role_arn = arn:aws:iam::123456789012:role/ProductionAccessRole
source_profile = default
```
