### ISSUE TITLE
Configure on client securely

### ISSUE THREAD

**Issue by merlinpatt** [peerlibrary/meteor-aws-sdk#28]
I've gotten AWS set up and can list S3 objects on the server using the sync methods given.

But when I do the same thing on the client (not using sync methods), I get the error `Missing credentials in config(…)`. The easy, but insecure fix, is to update the config on the client.

So how do I configure the credentials on the client securely?

**Comment by mitar** [comment]
I think [this documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html) explains how to do that.
