### ISSUE TITLE
TypeError: AWS.CloudSearchDomain is not a function

### ISSUE THREAD

**Issue by imakshath** [peerlibrary/meteor-aws-sdk#29]
I have installed this module in my meteor app. While I am trying to access 

> CloudSearchDomain

Its showing `TypeError: AWS.CloudSearchDomain is not a function`. I have console the AWS object which doesn't contain  `CloudSearchDomain` 
![selection_035](https://cloud.githubusercontent.com/assets/9428527/13277180/e2ffe4c0-daec-11e5-9225-bdebba8b26ef.png)

**Comment by mitar** [comment]
This package just wraps the official package. So not sure why there would not be `CloudSearchDomain`.

**Comment by akshath4u** [comment]
@mitar ..Is there any way to fix this issue?

**Comment by mitar** [comment]
I do not know. Feel free to look into it and if you find a fix propose a pull request.

**Comment by gkrizek** [comment]
@akshath4u Do you have a code sample?

**Comment by mitar** [comment]
Maybe fixed with update to latest upstream version.
