### ISSUE TITLE
[MAJOR] Causes total breakage of Accounts.createUser

### ISSUE THREAD

**Issue by ffxsam** [peerlibrary/meteor-aws-sdk#31]
To reproduce:

```
$ meteor create tmp
$ cd tmp
$ meteor add peerlibrary:aws-sdk accounts-password
$ meteor
```

Then run `meteor shell` and type:

    Accounts.createUser({email: 'you@user.net', password: 'test'});

This causes the server to bomb out.

**Comment by mitar** [comment]
Interesting. I have no idea where is this coming from. Can you find where is the exception coming from?

**Comment by ffxsam** [comment]
Actually, you can close this. It's a bug in Meteor, as of 1.3.2. Details: https://github.com/meteor/meteor/issues/7095
