### ISSUE TITLE
Huge Bundle Size because of this package

### ISSUE THREAD

**Issue by vladejs** [peerlibrary/meteor-aws-sdk#34]
Hi, first of all, this package is great because it made very simple the work with AWS services.

My concern is that, even if I only use one service, this package is giving me +900kb in JS that I don't use at all.

Is there a way to configure the package to compile only with the services I want?

I know that the standard aws-sdk from npm can be re-compiled to only the services I want, but, using this package I have no clue on how to accomplish the task.

Any help?

**Comment by mitar** [comment]
You are using this on the package client side?

Hm, yes. Probably this package could be migrated to use `ecmascript` package and a very thin `mainModule` file. And then you could import other files on demand.

I currently do not have time to look into this though, so a PR might be welcome.

**Comment by vladejs** [comment]
The issue is that it is using the (compiled with all services) JS file from
aws-sdk (/dist/aws-sdk.js)

2017-07-31 14:04 GMT-05:00 Mitar <notifications@github.com>:

**Comment by mitar** [comment]
Probably these days we could use non-dist file and leave it to Meteor to combine all files through imports.

**Comment by vladejs** [comment]
I'm afraid AWS SDK is more complex than just importing the service you
wanna use.

They have a browser builder tool, which you can use to recompile the
library with the services you want.

I can do that myself, but its like a hack. (recompile the library and
dropit on the dist folder inside peerlibrary under
/meteor/install/path/packages/ )

2017-07-31 14:16 GMT-05:00 Mitar <notifications@github.com>:

**Comment by mitar** [comment]
Not sure how Meteor tool chain can support you here? If you know of a way this package could fix this, tell.

**Comment by mitar** [comment]
Closing this because I do not think much can be done here. But if anyone figures how to do it, PRs are welcome.

**Comment by MrSpark2591** [comment]
I have updated forked project which makes it possible to include the package on server only.
This way you can reduce bundle size. (for all other usage make meteor function to perform task for clients.)
 [https://github.com/Fasal-Tech/meteor-aws-sdk.git](url)

**Comment by mitar** [comment]
Are you interested in making PR against this repo for this change?

**Comment by MrSpark2591** [comment]
@mitar here's  [PR](https://github.com/peerlibrary/meteor-aws-sdk/pull/39)

**Comment by mitar** [comment]
With 2.598.0_1 there is now lazy loading on the client.
