### ISSUE TITLE
s3.putObjectTagging is not a function

### ISSUE THREAD

**Issue by MileanCo** [peerlibrary/meteor-aws-sdk#35]
Im getting this error... seems like it's not implemented?!
`TypeError: s3.putObjectTagging is not a function`

It's defined in the AWS JS SDK: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObjectTagging-property

**Comment by mitar** [comment]
This package is just a simple wrapper. Since which version is that function around? Maybe it is not in the version used in this package.

**Comment by MileanCo** [comment]
Ahh okay! I'm using 
peerlibrary:aws-sdk@2.4.9_1
Meteor 1.6.1

The latest version of aws-sdk-js (2.193.0) has  this function: [putObjectTagging](https://github.com/aws/aws-sdk-js/search?utf8=%E2%9C%93&q=putObjectTagging&type=)

**Comment by mitar** [comment]
So did this function appear between 2.4.9 and 2.193.0?

**Comment by MileanCo** [comment]
There are [tons of changes](https://github.com/aws/aws-sdk-js/tree/master/.changes ) since 2.4.9. Can you update this package to use the latest AWS SDK? I'm sure there's other functionality missing as well, not just s3.putObjectTagging()

**Comment by MileanCo** [comment]
I just created a pull-request with the latest aws-sdk-js version. Can you merge and deploy to npm? It works with my local testing.

**Comment by mitar** [comment]
Released. Thanks.
