### ISSUE TITLE
Should I use this or just directly as an NPM package?

### ISSUE THREAD

**Issue by mizzao** [peerlibrary/meteor-aws-sdk#38]
It seems like the main change is to make server side methods Fibers-based instead of callbacks. Is that right?

Do the typings also work as if I had installed `aws-sdk` normally?

**Comment by mitar** [comment]
> It seems like the main change is to make server side methods Fibers-based instead of callbacks. Is that right?

Yes.

> Do the typings also work as if I had installed aws-sdk normally?

No idea about that.

**Comment by mizzao** [comment]
What's the difference between the sync call here...

```
const { AvailableBalance } = AWS.mturk.getAccountBalanceSync();
```

...and the normal `Promise`-based AWS API?

```
const { AvailableBalance } = await AWS.mturk.getAccountBalance().promise();
```

Do you know if the promise version would make Meteor's Fibers-based code confused?

cc @ejolly

**Comment by mitar** [comment]
If that is Meteor promise, I think things should just work: https://github.com/meteor/meteor/tree/devel/packages/promise

**Comment by mizzao** [comment]
What does "Meteor promise" mean? It is just the native Promise that the AWS SDK depends on: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-promises.html

Does Meteor have a specific type of Promise it depends on?

**Comment by mitar** [comment]
Yes, I think you can use theirs. Generally one can switch the implementation in many programs.
